### ISSUE TITLE
D register and possible bug?

### ISSUE THREAD

**Issue by wrm-za** [gorsat/6809#10]
Just found this, thanks, going to make my life a lot easier.

I'm running the "buggy" monitor from sbc09 (https://github.com/6809/sbc09)

1. Please add support for the D register "pshs d" instead of "pshs a,b"
2. When compiling monitor.asm I get an error on line 1867,  unexpected character '"'. There's no difference between this line and the dozens before it. Apologies, I have never used Rust before (and having read up on it to get this going, it looks a lot more streamlined than the C + Makefile environment I'm used to, and don't get me started on cmake...) so I have no idea how to debug this myself.
3. This compiles:
      "label fdb  fn1,fn2,fn3,fn4 ; comment".
   This fails with "missing number or label"
      "label fdb  fn1,fn2,fn3,fn4 ; comment," <- note comma at end.

Thanks!

**Comment by gorsat** [comment]
Hi. Thanks for the issue. 
1. I added support for psh and pul D
2. monitor.asm has errors on lines 1864 and 1867 where the fcb directives should be fcc. Just change both of those to fcc and it builds.
3. I fixed a bunch of parsing issues related to comments on fdb and fcb directives.

Let me know if you run into anything else!

**Comment by wrm-za** [comment]
Hiya

That was quick!
>    * I added support for psh and pul D
Thanks!
>    * monitor.asm has errors on lines 1864 and 1867 where the fcb 
> directives should be fcc. Just change both of those to fcc and it builds.
Oh I see. Sheesh I should have picked that up. My bad.
>    * I fixed a bunch of parsing issues related to fdb and fcb directives.
Great.

I have a feeling that I will be learning at least a bit of Rust in the future.

W
