### ISSUE TITLE
Support LIB directive

### ISSUE THREAD

**Issue by darkstar007** [gorsat/6809#9]
Flex Assembler has a 'LIB' directive which is essentially an include directive ([doc](http://www.flexusergroup.com/flexusergroup/pdfs/asmb.pdf) - page 37) which isn't currently supported - but it would be nice if it was!

Thanks,
Matt

**Comment by gorsat** [comment]
Handy feature. I'll see how much surgery this would require.

**Comment by gorsat** [comment]
I've looked into this a bit more. The way LIB is described seems fraught with potential issues -- certainly would be in this current codebase. The definition seems insufficient. Maybe there's more documentation somewhere that would temper my concerns.

One concern I have is about the position of LIB code in the resulting binary's address space. If there are one or more ORG directives in the file referenced by LIB then how should that impact the result? Should any overlapping segments that result from one or more LIBs be flagged as an assembler error, or a warning or just ignored? If the latter, then which segments "win" and get top billing in the resulting binary? And how should the source that follows the LIB be placed in memory? And does that change if the LIB is not a single, contiguous binary object (e.g., it has two or more ORGs -- and assuming we wouldn't want to just assume all the empty space between them is used by the LIB).

If LIB were defined as requiring the referenced file to contain position independent code (namely: no ORG directives; the code would assemble into one, position independent, contiguous binary object), then I think things would be less problematic, but maybe it would be less useful?

Also, the doc doesn't explain how (or if) labels in the LIB are carried through to the containing source or how that might change (or not) with nested LIBs (e.g., Root->LIB1->LIB2; Can you see LIB2 labels from Root?) I assume labels must be exposed or else referencing code in the LIB would be pretty awkward, but this wasn't explained in the doc. I'm envisioning a LIB file as being something like "my_tcpip_lib.asm" with several entry points that you want to reference.

As an alternative to LIB, adding some form of "include" functionality (probably would look more like the .copy directive described in this [TI assembler doc](https://downloads.ti.com/docs/esd/SPNU118O/Content/SPNU118O_HTML/assembler_directives.html#IDcopyincludedesc)) would provide similar functionality while also being fairly straightforward to define and implement. And it would automatically benefit from all the existing error checking. 

**Would "include" cover the cases you care about?** 

_This is all reminding me of the broader topic of linking. There are some big assembly language projects composed of dozens of files. Building those requires a linker with well defined semantics around things like code portability and symbol visibility. I should add "build a linker" to my todo list._

**Comment by darkstar007** [comment]
Hi,

Thanks for looking into this.

Yeah, I think 'include' would cover the things I care about.

Thanks,
Matt

**Comment by gorsat** [comment]
I added an .include directive (e.g. "   .include sub_dir/my_lib.asm") in [this commit](https://github.com/gorsat/6809/commit/22029878f7b63bed2f9f44ae68281529e1a07a1f). I also added a couple of tests for it, but my coverage is pretty light. Please let me know if you encounter any issues. I haven't added any documentation for it yet. The new test files provide simple examples. I'll keep this issue open until the feature is documented and any known problems are resolved. 

A quick way to see this in action is:
```
cargo run -- test/file1.asm -lr
```

Where file1.asm is just:
```
; this is file1
    lda #1
    .include include/file2.asm
    swi
; this is the end of file1
;! a=#0
;! b=#3
```

**Comment by darkstar007** [comment]
Cool. Thanks! I'll give it a try.
